name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
          --tag calm329/gfe-auth-server:latest \
          --build-arg NEXT_PUBLIC_DEFAULT_WEBSITE_URL=${{ vars.NEXT_PUBLIC_DEFAULT_WEBSITE_URL }} \
          --build-arg NEXT_PUBLIC_TERMS_URL=${{ vars.NEXT_PUBLIC_TERMS_URL }} \
          --build-arg NEXT_PUBLIC_PRIVACY_URL=${{ vars.NEXT_PUBLIC_PRIVACY_URL }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push calm329/gfe-auth-server:latest
